version = 0.1

[default.deploy.parameters]
stack_name = "codebase-guardian-app"
resolve_s3 = true
s3_prefix = "codebase-guardian-app"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
